name: PRKraft Communications Consultants
favicon: null
layout_spectrum: 0.01337
typography_spectrum: 0.7545
title: Making the right headlines since 1998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2fa'
    - '#202020'
    - '#d40022'
    - '#946244'
    - '#78a1ff'
  brandStrength: 0.7445631455630064
  lightness: 0.3451889115385711
  saturation: 0.8782473388127983
  rhythmicContrast: 0.66955401818268
purpose: []
