name: PRKraft Communications Consultants
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7445631455630064
  lightness: 0.3451889115385711
  saturation: 0.8782473388127983
  rhythmicContrast: 0.66955401818268
purpose: []
